export { default as menu } from "./menu.svg";
export { default as close } from "./close.svg";
export { default as curve } from "./curve.svg";
export { default as light } from "./light.png";
export { default as link } from "./link.png";
export { default as spark } from "./spark.png";
export { default as mobileCurve } from "./mobileCurve.svg";
export { default as bobble } from "./bobble.png";
export { default as man } from "./man.png";
export { default as idea } from "./idea.png";
export { default as lady } from "./lady.png";
export { default as ellipse } from "./criteria-ellipse.svg";
export { default as criteria } from "./criteria-illustrator.png";
export { default as faq } from "./faq.png";
export { default as faceebook } from "./faceebook.svg";
export { default as instagram } from "./instagram.svg";
export { default as linkedin } from "./linkedin.svg";
export { default as x } from "./x.svg";
export { default as location } from "./location.svg";
export { default as phone } from "./phone.svg";
export { default as liberty } from "./Liberty company logo white colour.png";
export { default as libertyPay } from "./Liberty company logo white.png";
export { default as paybox } from "./Paybox.png";
export { default as winwise } from "./Winwise logo White colour 1.png";
export { default as wisper } from "./wisper logo white.png";
export { default as vizual } from "./vizual.png";
export { default as trophy } from "./trophy.png";
export { default as gold_medal } from "./gold_medal 1.png";
export { default as silver_medal } from "./silver_medal 1.png";
export { default as bronze_medal } from "./bronze_medal 1.png";
export { default as lock } from "./lock.png";
export { default as shield } from "./shield.png";
export { default as listImg } from "./listimg.svg";
export { default as registerImage } from "./registerImage.png";
